name: Flow

on:
  pull_request:
    branches:
      - f24
  workflow_call:
  workflow_dispatch:

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: NPM Install
      uses: bahmutov/npm-install@v1
      with:
        useLockFile: false

    - name: Install Flow
      run: npm install --save-dev flow-bin

    - name: Initialize Flow
      run: npx flow init

    - name: Run Flow
      run: npx flow
